kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: squash
  labels:
    app: squash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: squash
        tier: dash
    spec:
      containers:
        - name: nginx
          imagePullPolicy: "Always"
          image: lsstsqre/squash-nginx:{{ TAG }}
          lifecycle:
            preStop:
              exec:
                command: ['/usr/sbin/nginx','-s','quit']
          volumeMounts:
            - name: nginx-conf
              mountPath: '/etc/nginx/conf.d'
            - name: tls-certs
              mountPath: '/etc/tls'
        - name: dash
          imagePullPolicy: "Always"
          image: lsstsqre/squash:{{ TAG }}
          ports:
            - name: http
              containerPort: 8000
          env:
          - name: SQUASH_API_URL
            value: {{ SQUASH_API_URL }}
          - name: SQUASH_GRAPHQL_URL
            value: {{ SQUASH_GRAPHQL_URL }}
          - name: SQUASH_BOKEH_URL
            value: {{ SQUASH_BOKEH_URL }}
          - name: ALLOWED_HOSTS
            value: {{ SQUASH_HOST }}
          - name: SQUASH_BOKEH_APPS 
            value: {{ SQUASH_BOKEH_APPS }}
          - name: SQUASH_MONITOR_APP
            value: {{ SQUASH_MONITOR_APP }}
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-certs
        - name: nginx-conf
          configMap:
            name: squash-nginx-conf
            items:
              - key: 'nginx.conf'
                path: 'nginx.conf'

