apiVersion: v1
kind: Service
metadata:
  name: squash-dash
  labels:
    app: squash
spec:
  selector:
    app: squash
    tier: dash
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
